# Generated by Django 4.0.3 on 2022-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'Django Admin'), (1, 'Super Admin'), (2, 'Business Admin'), (3, 'General Manager'), (4, 'Chief Accountant'), (5, 'Property Owner'), (6, 'Property Manager'), (7, 'Property Accountant'), (8, 'Staff'), (9, 'Tenant'), (10, 'Lawyer')]),
        ),
    ]
