# Generated by Django 4.0.6 on 2023-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_userownershipprofile_user_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
