# Generated by Django 4.0.6 on 2023-10-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
