# Generated by Django 4.0.3 on 2022-05-27 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_preference', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'criminal'), ('tax', 'Tax'), ('corporate', 'Corporate'), ('family', 'Family'), ('civil_litigation', 'Civil Litigation'), ('real_estate', 'Real Estate'), ('labour', 'Labour'), ('contract', 'Contract'), ('employment', 'Employment')], max_length=32)),
                ('bar', models.CharField(blank=True, max_length=32, null=True)),
                ('court', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
