# Generated by Django 4.0.3 on 2022-05-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_lawyerdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LawyerDetails',
            new_name='Lawyer',
        ),
    ]
