# Generated by Django 4.0.6 on 2024-03-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_premium_expiry_date_user_premium_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audio_permission',
            field=models.BooleanField(default=False),
        ),
    ]
