# Generated by Django 4.0.6 on 2024-09-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_audio_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveBigIntegerField(choices=[(1, 'Super Admin'), (2, 'Sub Admin'), (3, 'Customer'), (4, 'Partner')]),
        ),
    ]
