# Generated by Django 4.0.6 on 2024-09-08 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_user_validity_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveBigIntegerField(choices=[(1, 'Super Admin'), (2, 'Sub Admin'), (3, 'Customer'), (4, 'Partner'), (5, 'Retailer')]),
        ),
        migrations.CreateModel(
            name='PartnerAndRetailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
