# Generated by Django 4.0.3 on 2022-07-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userownershipprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
        migrations.DeleteModel(
            name='UserOwnershipProfile',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
