# Generated by Django 4.0.6 on 2024-09-08 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_user_user_type_partnerandretailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerandretailer',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerandretailer',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailers', to=settings.AUTH_USER_MODEL),
        ),
    ]
