# Generated by Django 4.0.6 on 2024-09-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_partnerandretailer_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
