# Generated by Django 4.0.6 on 2024-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerandretailer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerandretailer',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='partnerandretailer',
            name='name',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
