# Generated by Django 4.0.6 on 2024-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_partnerandretailer_email_partnerandretailer_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='premium_user',
            new_name='diamond_user',
        ),
        migrations.AddField(
            model_name='user',
            name='gold_user',
            field=models.BooleanField(default=False),
        ),
    ]
