version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/srv/tech_plotz/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis

  celery:
    build: .
    command: celery -A tech_plotz worker -l info -Q tech_plotz
    volumes:
      - .:/srv/tech_plotz/app/
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    command: celery -A tech_plotz beat -l info
    volumes:
      - .:/srv/tech_plotz/app/
    depends_on:
      - django
      - redis
