# Generated by Django 4.0.6 on 2023-08-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_favorite_added_on_helpdesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='reply_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
