# Generated by Django 4.0.6 on 2023-08-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_helpdesk_reply_helpdesk_reply_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
