# Generated by Django 4.0.6 on 2024-01-20 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_podcast_is_trashed_playlist_is_trashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0004_helpdesk_is_replied'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_audios', to='admin_panel.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
