# Generated by Django 4.0.6 on 2024-01-20 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0007_remove_podcast_is_trashed_playlist_is_trashed'),
        ('customer', '0005_favoriteaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_progresses', to='admin_panel.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_progresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
