# Generated by Django 4.0.6 on 2024-09-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_purchasepodcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
