# Generated by Django 4.0.6 on 2024-09-14 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_codes_redeemed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='sent_to',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
