# Generated by Django 4.0.6 on 2024-09-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0002_alter_accesscode_redeemed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
