# Generated by Django 4.0.6 on 2023-08-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_playlist_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_lists', to='admin_panel.podcast'),
        ),
    ]
