# Generated by Django 4.0.6 on 2023-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_playlist_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_status', models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance')], default='active', max_length=30)),
            ],
        ),
    ]
