# Generated by Django 4.0.6 on 2024-01-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_podcast_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='position',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
