# Generated by Django 4.0.6 on 2024-01-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_playlist_position_podcast_is_trashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='is_trashed',
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
