# Generated by Django 4.0.6 on 2024-09-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_podcast_is_trashed_playlist_is_trashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('validity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_diamond',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
