# Generated by Django 4.0.6 on 2024-11-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_package_podcast_is_diamond_podcast_is_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
