# Generated by Django 4.0.6 on 2024-12-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_podcast_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='position',
            field=models.FloatField(default=0),
        ),
    ]
