# Generated by Django 4.0.6 on 2023-01-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('meeting_date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('minutes', models.TextField(blank=True, null=True)),
                ('document', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_district', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('relation', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('land', 'Land'), ('house_flat_villa', 'House/Flat/Villa'), ('warehouse', 'Warehouse'), ('shop_showroom', 'Shop/Showroom'), ('office', 'Office'), ('agriculture', 'Agriculture'), ('pg', 'PG')], max_length=200, null=True)),
                ('options', models.CharField(blank=True, choices=[('rent', 'Rent'), ('sale', 'Sale'), ('both', 'Both'), ('lease', 'Lease')], max_length=200, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('measurement_unit', models.CharField(blank=True, choices=[('sqft', 'Sqft'), ('acre', 'Acre'), ('cent', 'Cent'), ('sqm', 'Sq.m'), ('sqyrd', 'Sq.yrd'), ('sqkm', 'Sq.km'), ('sqmile', 'Sq.mile'), ('sqinch', 'Sq.inch')], max_length=200, null=True)),
                ('corporation', models.BooleanField(default=False)),
                ('municipality', models.BooleanField(default=False)),
                ('village', models.BooleanField(default=False)),
                ('panchayat', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('taluk', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('zoning', models.CharField(blank=True, max_length=200, null=True)),
                ('natural_element_present_in_site', models.CharField(blank=True, max_length=200, null=True)),
                ('water_source', models.CharField(blank=True, max_length=200, null=True)),
                ('google_location_url', models.URLField(blank=True, max_length=500, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_personal_address', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_state', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_district', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('ownership', models.CharField(blank=True, max_length=200, null=True)),
                ('survey_plan', models.URLField(blank=True, null=True)),
                ('area_plan', models.URLField(blank=True, null=True)),
                ('adhaar_copy', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=16)),
                ('document', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.transactioncategory')),
            ],
        ),
    ]
